export const templatesToAdd = [
  {
    name: "default_template_1",
    isPublic: true,
    template: {
      outerContainer: {
        position: "relative",
        height: 1000,
        backgroundColor: "#fff",
      },
      beforeImage: {
        position: { x: 20 * 2, y: 20 * 2 },
        size: { width: "44%", height: "92%" },
        containerStyle: { backgroundColor: "#000" },
        imageStyle: { width: "100%", height: "100%", objectFit: "cover" },
      },
      afterImage: {
        position: { x: 260 * 2, y: 20 * 2 },
        size: { width: "44%", height: "92%" },
        containerStyle: { backgroundColor: "#000" },
        imageStyle: { width: "100%", height: "100%", objectFit: "cover" },
      },
      images: [],
      texts: [],
      divs: [],
    },
  },
  {
    name: "default_template_2",
    isPublic: true,
    template: {
      outerContainer: {
        position: "relative",
        height: 500 * 2,
        backgroundColor: "#fff",
      },
      beforeImage: {
        position: { x: 20 * 2, y: 20 * 2 },
        size: { width: "44%", height: "92%" },
        containerStyle: {
          backgroundColor: "#000",
          boxShadow: "0px 0px 10px rgba(0, 0, 0, 0.4)",
        },
        imageStyle: { width: "100%", height: "100%", objectFit: "cover" },
      },
      afterImage: {
        position: { x: 260 * 2, y: 20 * 2 },
        size: { width: "44%", height: "92%" },
        containerStyle: {
          backgroundColor: "#000",
          boxShadow: "0px 0px 10px rgba(0, 0, 0, 0.4)",
        },
        imageStyle: { width: "100%", height: "100%", objectFit: "cover" },
      },
      images: [],
      texts: [],
      divs: [],
    },
  },
  {
    name: "default_template_3",
    isPublic: true,
    template: {
      outerContainer: {
        position: "relative",
        height: 500 * 2,
        backgroundColor: "#000",
      },
      beforeImage: {
        position: { x: 20 * 2, y: 20 * 2 },
        size: { width: "44%", height: "92%" },
        containerStyle: {
          backgroundColor: "#000",
        },
        imageStyle: { width: "100%", height: "100%", objectFit: "cover" },
      },
      afterImage: {
        position: { x: 260 * 2, y: 20 * 2 },
        size: { width: "44%", height: "92%" },
        containerStyle: {
          backgroundColor: "#000",
        },
        imageStyle: { width: "100%", height: "100%", objectFit: "cover" },
      },
      images: [],
      texts: [],
      divs: [],
    },
  },
  {
    name: "default_template_4",
    isPublic: true,
    template: {
      outerContainer: {
        position: "relative",
        height: 500 * 2,
        backgroundColor: "#000",
        overflow: "hidden",
      },
      beforeImage: {
        position: { x: 0 * 2, y: 0 * 2 },
        size: { width: "50%", height: "100%" },
        containerStyle: {
          backgroundColor: "#000",
        },
        imageStyle: { width: "100%", height: "100%", objectFit: "cover" },
      },
      afterImage: {
        position: { x: 250 * 2, y: 0 * 2 },
        size: { width: "50%", height: "100%" },
        containerStyle: {
          backgroundColor: "#000",
        },
        imageStyle: { width: "100%", height: "100%", objectFit: "cover" },
      },
      images: [],
      texts: [
        {
          content: `${new Array(1000).fill("0").join("")}`,
          position: { x: 0, y: 478 * 2 },
          containerStyle: {},
          textStyle: {
            position: "absolute",
            backgroundColor: "rgba(0, 0, 0, 0.4)",
            textWrap: "nowrap",
            fontSize: 20 * 2,
            color: "transparent",
            fontFamily: "Arial",
          },
        },
        {
          content: "Before",
          position: { x: 125 * 2, y: 478 * 2 },
          containerStyle: {},
          textStyle: {
            position: "absolute",
            transform: "translate(-50%)",
            textWrap: "nowrap",
            fontSize: 20 * 2,
            fontFamily: "Arial",
            color: "#fff",
            zIndex: 1,
          },
        },
        {
          content: "After",
          position: { x: 375 * 2, y: 478 * 2 },
          containerStyle: {},
          textStyle: {
            position: "absolute",
            transform: "translate(-50%)",
            textWrap: "nowrap",
            fontSize: 20 * 2,
            fontFamily: "Arial",
            color: "#fff",
            zIndex: 1,
          },
        },
      ],
      divs: [],
    },
  },
  {
    name: "default_template_5",
    isPublic: true,
    template: {
      outerContainer: {
        position: "relative",
        height: 500,
        backgroundColor: "#fff",
      },
      beforeImage: {
        position: { x: 10, y: 70 },
        size: { width: "47%", height: "70%" },
        containerStyle: { backgroundColor: "#000" },
        imageStyle: { width: "100%", height: "100%", objectFit: "cover" },
      },
      afterImage: {
        position: { x: 255, y: 70 },
        size: { width: "47%", height: "70%" },
        containerStyle: { backgroundColor: "#000" },
        imageStyle: { width: "100%", height: "100%", objectFit: "cover" },
      },
      images: [],
      texts: [],
      divs: [],
    },
  },
  {
    name: "default_template_6",
    isPublic: true,
    template: {
      outerContainer: {
        position: "relative",
        height: 500 * 2,
        backgroundColor: "#475772",
      },
      beforeImage: {
        position: { x: 22 * 2, y: 102 * 2 },
        size: { width: "43.5%", height: "60%" },
        containerStyle: {
          borderBottomWidth: 48 * 2,
          borderBottomColor: "#fff",
          borderBottomStyle: "solid",
          borderRadius: 7 * 2,
          overflow: "hidden",
        },
        imageStyle: {
          width: "100%",
          height: "100%",
          objectFit: "cover",
          backgroundColor: "#000",
        },
      },
      afterImage: {
        position: { x: 262 * 2, y: 102 * 2 },
        size: { width: "43.5%", height: "60%" },
        containerStyle: {
          borderBottomWidth: 48 * 2,
          borderBottomColor: "#fff",
          borderBottomStyle: "solid",
          borderRadius: 7 * 2,
          overflow: "hidden",
        },
        imageStyle: {
          width: "100%",
          height: "100%",
          objectFit: "cover",
          backgroundColor: "#000",
        },
      },
      images: [
        {
          src: "https://clinic-os.com/user-app-assets/template-logos/template-logo-0003.png",
          position: { x: 22 * 2, y: 415 * 2 },
          size: { width: "15%", height: "15%" },
          containerStyle: {
            zIndex: 1,
          },
          imageStyle: {
            width: "100%",
            height: "100%",
            objectFit: "fill",
          },
        },
      ],
      texts: [
        {
          content: "Before",
          position: { x: 135 * 2, y: 365 * 2 },
          containerStyle: {},
          textStyle: {
            position: "absolute",
            transform: "translateX(-50%)",
            textWrap: "nowrap",
            fontSize: 20 * 2,
            color: "#475772",
            fontFamily: "InterRegular",
            zIndex: 2,
          },
        },
        {
          content: "After",
          position: { x: 375 * 2, y: 365 * 2 },
          containerStyle: {},
          textStyle: {
            position: "absolute",
            transform: "translateX(-50%)",
            textWrap: "nowrap",
            fontSize: 20 * 2,
            color: "#475772",
            fontFamily: "InterRegular",
            zIndex: 2,
          },
        },
        {
          content: "PROCEDURE TITLE",
          position: { x: 250 * 2, y: 40 * 2 },
          containerStyle: {},
          textStyle: {
            position: "absolute",
            transform: "translateX(-50%)",
            textWrap: "nowrap",
            fontSize: 31 * 2,
            color: "#fff",
            fontFamily: "SplineSansRegular",
            zIndex: 2,
          },
        },
        {
          content: "Contact Info Etc",
          position: { x: 400 * 2, y: 440 * 2 },
          containerStyle: {},
          textStyle: {
            position: "absolute",
            transform: "translateX(-50%)",
            textWrap: "nowrap",
            fontSize: 22,
            color: "#fff",
            fontFamily: "InterRegular",
            zIndex: 2,
          },
        },
        {
          content:
            "Short procedure description or necessary information. Keep info to two lines maximum.",
          position: { x: 240 * 2, y: 440 * 2 },
          containerStyle: {},
          textStyle: {
            position: "absolute",
            transform: "translateX(-50%)",
            width: 250 * 2,
            fontSize: 11 * 2,
            color: "#fff",
            fontFamily: "InterRegular",
            zIndex: 2,
          },
        },
      ],
      divs: [],
    },
  },
  {
    name: "default_template_7",
    isPublic: true,
    template: {
      outerContainer: {
        position: "relative",
        height: 500 * 2,
        backgroundColor: "#413D3D",
      },
      beforeImage: {
        position: { x: 22 * 2, y: 155 * 2 },
        size: { width: "44%", height: "57%" },
        containerStyle: { backgroundColor: "#000" },
        imageStyle: { width: "100%", height: "100%", objectFit: "cover" },
      },
      afterImage: {
        position: { x: 255 * 2, y: 185 * 2 },
        size: { width: "44%", height: "57%" },
        containerStyle: { backgroundColor: "#000" },
        imageStyle: { width: "100%", height: "100%", objectFit: "cover" },
      },
      images: [
        {
          src: "https://clinic-os.com/user-app-assets/template-logos/template-logo-0003.png",
          position: { x: 395 * 2, y: 45 * 2 },
          size: { width: "14%", height: "14%" },
          containerStyle: {
            zIndex: 1,
          },
          imageStyle: {
            width: "100%",
            height: "100%",
            objectFit: "fill",
          },
        },
      ],
      texts: [
        {
          content: "Procedure Title",
          position: { x: 22 * 2, y: 45 * 2 },
          containerStyle: {},
          textStyle: {
            textWrap: "nowrap",
            fontSize: 42 * 2,
            color: "#fff",
            fontFamily: "InstrumentSerifRegular",
            zIndex: 2,
          },
        },
        {
          content:
            "Short procedure description or necessary information. Keep info to two lines maximum.",
          position: { x: 22 * 2, y: 100 * 2 },
          containerStyle: {},
          textStyle: {
            position: "absolute",
            width: 250 * 2,
            fontSize: 11 * 2,
            color: "#fff",
            fontFamily: "InterRegular",
            zIndex: 2,
          },
        },
        {
          content: "Before",
          position: { x: 133 * 2, y: 420 * 2 },
          containerStyle: {},
          textStyle: {
            position: "absolute",
            transform: "translateX(-50%)",
            textWrap: "nowrap",
            fontSize: 22 * 2,
            backgroundColor: "#fff",
            paddingTop: 3 * 2,
            paddingBottom: 3 * 2,
            width: 170 * 2,
            textAlign: "center",
            color: "#413D3D",
            fontFamily: "InstrumentSerifRegular",
            zIndex: 2,
          },
        },
        {
          content: "After",
          position: { x: 366 * 2, y: 168 * 2 },
          containerStyle: {},
          textStyle: {
            position: "absolute",
            transform: "translateX(-50%)",
            textWrap: "nowrap",
            fontSize: 22 * 2,
            backgroundColor: "#fff",
            paddingTop: 3 * 2,
            paddingBottom: 3 * 2,
            width: 170 * 2,
            textAlign: "center",
            color: "#413D3D",
            fontFamily: "InstrumentSerifRegular",
            zIndex: 2,
          },
        },
      ],
      divs: [],
    },
  },
  {
    name: "default_template_8",
    isPublic: true,
    template: {
      outerContainer: {
        position: "relative",
        height: 500,
        backgroundColor: "#F8E7E3",
      },
      beforeImage: {
        position: { x: 30, y: 130 },
        size: { width: "42%", height: "57%" },
        containerStyle: {
          rotate: "-6deg",
          borderTopWidth: 8,
          borderLeftWidth: 8,
          borderBottomWidth: 48,
          borderRightWidth: 8,
          borderColor: "#fff",
          borderStyle: "solid",
          boxShadow: "0px 4px 4px 0px rgba(0, 0, 0, 0.25)",
        },
        imageStyle: {
          width: "100%",
          height: "100%",
          objectFit: "cover",
          backgroundColor: "#000",
        },
      },
      afterImage: {
        position: { x: 220, y: 105 },
        size: { width: "42%", height: "57%" },
        containerStyle: {
          rotate: "9deg",
          borderTopWidth: 8,
          borderLeftWidth: 8,
          borderBottomWidth: 48,
          borderRightWidth: 8,
          borderColor: "#fff",
          borderStyle: "solid",
          boxShadow: "0px 4px 4px 0px rgba(0, 0, 0, 0.25)",
        },
        imageStyle: {
          width: "100%",
          height: "100%",
          objectFit: "cover",
          backgroundColor: "#000",
        },
      },
      images: [
        {
          src: "https://clinic-os.com/user-app-assets/template-logos/template-logo-0003.png",
          position: { x: 408, y: 32 },
          size: { width: "12%", height: "12%" },
          containerStyle: {
            zIndex: 1,
          },
          imageStyle: {
            width: "100%",
            height: "100%",
            objectFit: "fill",
          },
        },
      ],
      texts: [
        {
          content: "PROCEDURE TITLE",
          position: { x: 30, y: 40 },
          containerStyle: {},
          textStyle: {
            textWrap: "nowrap",
            fontSize: 27,
            color: "#000",
            zIndex: 2,
            fontFamily: "WorkSansMedium",
          },
        },
        {
          content: "Short procedure description or necessary information.",
          position: { x: 30, y: 80 },
          containerStyle: {},
          textStyle: {
            position: "absolute",
            width: 180,
            fontSize: 11,
            color: "#000",
            fontFamily: "InterRegular",
            zIndex: 2,
          },
        },
        {
          content: "BEFORE",
          position: { x: 95, y: 452 },
          containerStyle: {},
          textStyle: {
            position: "absolute",
            transform: "translateX(50%)",
            fontSize: 18,
            color: "#000",
            fontFamily: "WorkSansRegular",
            zIndex: 2,
          },
        },
        {
          content: "AFTER",
          position: { x: 275, y: 452 },
          containerStyle: {},
          textStyle: {
            position: "absolute",
            transform: "translateX(50%)",
            fontSize: 18,
            color: "#000",
            fontFamily: "WorkSansRegular",
            zIndex: 2,
          },
        },
      ],
      divs: [],
    },
  },
  {
    name: "default_template_9",
    isPublic: true,
    template: {
      outerContainer: {
        position: "relative",
        height: 500 * 2,
        backgroundColor: "#EDE6E1",
      },
      beforeImage: {
        position: { x: 50 * 2, y: 140 * 2 },
        size: { width: "38%", height: "59%" },
        containerStyle: {
          borderLeftWidth: 0 * 2,
          borderRightWidth: 0 * 2,
          borderBottomWidth: 0 * 2,
          borderTopWidth: 48 * 2,
          borderColor: "#fff",
          borderStyle: "solid",
          borderRadius: 7 * 2,
          overflow: "hidden",
        },
        imageStyle: {
          width: "100%",
          height: "100%",
          objectFit: "cover",
          backgroundColor: "#000",
        },
      },
      afterImage: {
        position: { x: 255 * 2, y: 170 * 2 },
        size: { width: "38%", height: "59%" },
        containerStyle: {
          borderLeftWidth: 0 * 2,
          borderRightWidth: 0 * 2,
          borderTopWidth: 0 * 2,
          borderBottomWidth: 48 * 2,
          borderColor: "#fff",
          borderStyle: "solid",
          borderRadius: 7 * 2,
          overflow: "hidden",
        },
        imageStyle: {
          width: "100%",
          height: "100%",
          objectFit: "cover",
          backgroundColor: "#000",
        },
      },
      images: [
        {
          src: "https://clinic-os.com/user-app-assets/template-logos/template-logo-0003.png",
          position: { x: 415 * 2, y: 18 * 2 },
          size: { width: "14%", height: "14%" },
          containerStyle: {
            zIndex: 1,
          },
          imageStyle: {
            width: "100%",
            height: "100%",
            objectFit: "fill",
          },
        },
        {
          src: "https://clinic-os.com/user-app-assets/template-other-images/x-0001.icon.png",
          position: { x: 30 * 2, y: 410 * 2 },
          size: { width: "10%", height: "10%" },
          containerStyle: {
            zIndex: 1,
          },
          imageStyle: {
            width: "100%",
            height: "100%",
            objectFit: "fill",
          },
        },
        {
          src: "https://clinic-os.com/user-app-assets/template-other-images/arrow-left-0001.icon.png",
          position: { x: 225 * 2, y: 265 * 2 },
          size: { width: "10%", height: "10%" },
          containerStyle: {
            zIndex: 1,
          },
          imageStyle: {
            width: "100%",
            height: "100%",
            objectFit: "fill",
          },
        },
        {
          src: "https://clinic-os.com/user-app-assets/template-other-images/heart-0001.icon.png",
          position: { x: 420 * 2, y: 145 * 2 },
          size: { width: "10%", height: "10%" },
          containerStyle: {
            zIndex: 1,
          },
          imageStyle: {
            width: "100%",
            height: "100%",
            objectFit: "fill",
          },
        },
      ],
      texts: [
        {
          content: "Procedure Title",
          position: { x: 250 * 2, y: 45 * 2 },
          containerStyle: {},
          textStyle: {
            position: "absolute",
            transform: "translateX(-50%)",
            textWrap: "nowrap",
            fontSize: 26 * 2,
            color: "#000",
            fontFamily: "WorkSansRegular",
            zIndex: 2,
          },
        },
        {
          content:
            "Short procedure description or necessary information. Keep info to two lines maximum.",
          position: { x: 250 * 2, y: 83 * 2 },
          containerStyle: {},
          textStyle: {
            position: "absolute",
            transform: "translateX(-50%)",
            textAlign: "center",
            width: 283 * 2,
            fontSize: 10 * 2,
            color: "#000",
            fontFamily: "WorkSansRegular",
            zIndex: 2,
          },
        },
        {
          content: "Before",
          position: { x: 85 * 2, y: 150 * 2 },
          containerStyle: {},
          textStyle: {
            position: "absolute",
            transform: "translateX(50%)",
            fontSize: 18 * 2,
            color: "#000",
            fontFamily: "WorkSansRegular",
            zIndex: 2,
          },
        },
        {
          content: "After",
          position: { x: 310 * 2, y: 430 * 2 },
          containerStyle: {},
          textStyle: {
            position: "absolute",
            transform: "translateX(50%)",
            fontSize: 18 * 2,
            color: "#000",
            fontFamily: "WorkSansRegular",
            zIndex: 2,
          },
        },
      ],
      divs: [],
    },
  },
];
